### ISSUE TITLE
[ENHANCEMENT] `units_dict` could be an Array

### ISSUE THREAD

**Issue by yawboakye** [olufotebig/intro_to_programming#1]
@olufotebig Since the keys for the [`units_dict`](https://github.com/olufotebig/intro_to_programming/blob/f132e2b2cd617028bd00522ecc5090c36e581f87/092716/fiw.rb#L3) are `0..9`, won't an `Array` be a better fit for the job? Like we discussed in class, we can see arrays as a type of hash whose keys are permanently integers.

**Comment by yawboakye** [comment]
Same goes for [`tens_dict`](https://github.com/olufotebig/intro_to_programming/blob/f132e2b2cd617028bd00522ecc5090c36e581f87/092716/fiw.rb#L16) and [`one_tens_dict`](https://github.com/olufotebig/intro_to_programming/blob/f132e2b2cd617028bd00522ecc5090c36e581f87/092716/fiw.rb#L28). Let me know what you think. More importantly I'm interested in why you chose a hash over an array, and whether arrays presented themselves as a good structure to hold that data. @olufotebig

**Comment by olufotebig** [comment]
@yawboakye I used the hash just for expressiveness, I can refactor the code to use arrays if they offer significant performance advantage

**Comment by yawboakye** [comment]
@olufotebig I'm not sure I understand what expressiveness means in this context. When I looked at the code I saw a reimplementation of Array: a hash whose keys are integers starting from 0, to speak of Array in terms of hash. In this case the apparent gain of a hash over an array is not apparent, and could rather prevent the reader from understanding your code in simple terms.
